version: "3.5"
services:
  api:
    # env_file:
    #   - .env.dist
    build:
      context: ./
      target: dev
    image: node:12.18.3-alpine-nest
    expose:
      - 4000
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    depends_on:
      - db
    command: npm run start:dev
  db:
    container_name: mysql_boiler
    image: mysql:8.0
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: mutual
      MYSQL_USER: mutual
      MYSQL_PASSWORD: mutual
    volumes:
      - mysql-boiler:/var/lib/mysql

volumes:
  mysql-boiler:
